### PR TITLE
Fix CI badge

### PR DESCRIPTION
**Pull request by tri-adam**
Fix CircleCI badge, as it's tied to repository location.

### CODE REVIEW

**Comment by EmmEff** [comment]
FYI, related issue with the godoc badge as well...

Also, the build shows a warning about using a third-party orb with CircleCI

**Comment by tri-adam** [comment]
@ikaneshiro / @dctrud are aware of the CI issue, should be fixed later today.

For godoc, I believe the URL is tied to the _module_ name, not the repo? https://godoc.org/github.com/hpcng/sif doesn't work...

**Comment by dctrud** [comment]
Yes the godoc stuff won't change until the `go.mod` module name is modified. That won't happen any time soon. It will be co-ordinated on a major release to avoid breaking plugin imports etc. etc.

**Comment by tri-adam** [comment]
Would highly discourage modifying the module name. That's a world of pain...

**Comment by tri-adam** [comment]
Fixed in #78

**Pull request closed without merging**
